# Generated by Django 3.0.3 on 2020-05-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_1', models.IntegerField()),
                ('dice_2', models.IntegerField()),
                ('dice_3', models.IntegerField()),
                ('dice_4', models.IntegerField()),
                ('dice_5', models.IntegerField()),
            ],
        ),
    ]
