# Generated by Django 3.0.3 on 2020-05-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='game_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
