# Generated by Django 3.0.3 on 2020-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0002_roll_game_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='game_no',
            field=models.IntegerField(unique=True),
        ),
    ]
