# Generated by Django 3.0.3 on 2020-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0004_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='total',
            field=models.IntegerField(),
        ),
    ]
