# Generated by Django 3.0.3 on 2020-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0005_auto_20200517_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='dices_amount',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
