# Generated by Django 3.0.3 on 2020-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dices', '0006_scores_dices_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='dice_1',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='dice_2',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='dice_3',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='dice_4',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='roll',
            name='dice_5',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
