document.addEventListener("DOMContentLoaded", function(){
    var img_1 = document.getElementById("img_1")
    var img_2 = document.getElementById("img_2")
    var img_3 = document.getElementById("img_3")
    var img_4 = document.getElementById("img_4")
    var img_5 = document.getElementById("img_5")
    var img_6 = document.getElementById("img_6")
    img_1.addEventListener("click", function(){console.log("Done")})
    img_2.addEventListener("click", function(){content1.style.display = "inline"})
    img_3.addEventListener("click", function(){content1.style.display = "inline"})
    img_4.addEventListener("click", function(){content1.style.display = "inline"})
    img_5.addEventListener("click", function(){content1.style.display = "inline"})
    img_6.addEventListener("click", function(){content1.style.display = "inline"})
})
